export const ioParams = [
  { value: 0, content: 'Y00运行指示' },
  { value: 1, content: 'Y01马达运行' },
  { value: 2, content: 'Y02马达正转' },
  { value: 3, content: 'Y03马达反转' },
  { value: 4, content: 'Y04润滑1' },
  { value: 5, content: 'Y05喷风1' },
  { value: 6, content: 'Y06电子凸轮1' },
  { value: 7, content: '电子凸轮2' },
  { value: 8, content: '电子凸轮3' },
  { value: 9, content: '电子凸轮4' },
  { value: 10, content: 'Y10' },
  { value: 11, content: 'Y11' },
  { value: 12, content: 'Y12' },
  { value: 13, content: 'Y13' },
  { value: 14, content: 'Y14' },
  { value: 15, content: 'Y15' },
  { value: 16, content: 'Y16离合1' },
  { value: 17, content: 'Y16离合2' },
  { value: 18, content: 'Y18过载复位' },
  { value: 19, content: 'Y19星行启动' },
  { value: 20, content: 'Y20三角启动' },
  { value: 21, content: '滑块上升' },
  { value: 22, content: '机油泵' },
  { value: 23, content: '调模阀' },
]
